### ISSUE TITLE
"postcss" value in "lang" atributte, fail to process .vue file

### ISSUE THREAD

**Issue by eulier1** [mstrlaw/nuxt-storybook#3]
```
<style lang="postcss" scoped>
.list {
  background: #EFF8FF;
}
</style>
```

This implementation doesn't work, but i think it's because not using the proper loader
![Screenshot from 2020-01-24 15-06-36](https://user-images.githubusercontent.com/12874996/73092566-a0743c00-3ebb-11ea-9b63-df0db30371a9.png)

**Comment by nonlinearcom** [comment]
I'm facing the same issue, is there any workaround for this?

**Comment by ghost** [comment]
You have to add the postcss-loader to the storybook webpack config iirc

```
module.exports = {
  module: {
    rules: [
      {
        test: /\.(post)?css$/,
        loaders: [
          'style-loader',
          'css-loader',
          {
            loader: 'postcss-loader',
            options: {
              config: { path: './.storybook/' }
            }
          }
        ],
        include: path.resolve(__dirname, '../')
      }
    ]
  }
}
```

**Comment by danihazler** [comment]
Hi there,

Having the same problem, changed my `main.js` many times in order to make it work, but had no success.
Ended up adding a question on Stackoverflow https://stackoverflow.com/questions/70835990/storybook-vuex-nuxt-config-postcss-how-to-make-them-work-together. 

Perhaps because I'm misunderstanding something due to the Storybook new version not having `config.js`, `addons.js` etc..?

Many thanks for any help :)

**Comment by mstrlaw** [comment]
Hey @danihazler 

I haven't touched this in a couple of years, I'm pretty sure there are better ways to do this nowadays 🤔
